### ISSUE TITLE
Missing CSS

### ISSUE THREAD

**Issue by camwoodward3** [Karritt/cse340-practice-Arritt#2]
It seems like some CSS is missing that is used for the products page. It's entirely necessary, but the CSS can useful to make the products page look nice!

Suggested Solution:
Change
```css
...
```

To 
```css

.products-container {
    margin: 2rem 0;
}

.grid-view {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
    gap: 1.5rem;
}

.grid-view, .products-container {
    display: none;
}

.details-view .product-card {
    display: flex;
    margin-bottom: 1.5rem;
    border-bottom: 1px solid #eee;
    padding-bottom: 1.5rem;
}

.product-card {
    border: 1px solid #ddd;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    transition: transform 0.3s ease;
}

.product-card:hover {
    transform: translateY(-5px);
}

.product-image {
    width: 100%;
    height: 200px;
    object-fit: cover;
}

.details-view .product-image {
    width: 200px;
    height: 150px;
    margin-right: 1.5rem;
}

.product-info {
    padding: 1rem;
}

.product-name {
    margin-top: 0;
    font-size: 1.2rem;
}

.product-price {
    font-weight: bold;
    color: #4a4a4a;
}

.view-toggle {
    margin-top: 2rem;
    text-align: center;
}

.view-toggle a {
    text-decoration: none;
    padding: 0.5rem 1rem;
    color: #333;
}

.view-toggle a.active {
    font-weight: bold;
    text-decoration: underline;
}
```
